### ISSUE TITLE
Different boards can not be built using Makefile targets

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [leaflabs/maple-bootloader#14]
It seems very strange that this repo contains a different branch for each target e.g. Maple, Maple mini etc

Wouldn't it be better to have one unified source with #defines in the Makefile for the Port and Pin numbers of DISC pin and the LED etc

So that a bootloader could be built by using Make maple-mini  or Maple maple-rev3  etc

**Comment by mbolivar** [comment]
Yes, it was crap to do it that way.

We've EOLed Maple, though, so while we'll take patches that fix it, I'm afraid we won't be making changes:

https://leaf-labs.squarespace.com/news/2015/3/27/maple-end-of-life-notice

Thanks,
Marti

**Comment by rogerclarkmelbourne** [comment]
Hi Marti

No worries. Yes I know that end of life was notified.

I've forked https://github.com/jonatanolofsson/maple-bootloader which does seem to be maintained, so will make changes to my fork and do a PR into https://github.com/jonatanolofsson/maple-bootloader

If Jonathan is no longer maintaining either, I'll probably make make a new repo and copy the latest files 

But I was hoping that possibly Jonatan would still be maintaining his repo

BTW. We're also going to remove RAM uploads, so that we can free up the 3K permanently allocated to the bootloader  over to the sketch and now that the bootloader is much smaller as it will compile with optimised, we will be changing our version of libmaple etc so that the sketch gets more of the Flash

We're also going to write a sketch that will be able to update the bootloader in a Maple or Maple mini's by using the EEPROM library - albeit at the owners own risk ;-)

BTW. Thanks for all your hard work in the first place.
Because LibMaple and the bootloader live on, in probably even greater numbers than when it was an official product.

**Comment by mbolivar** [comment]
Sounds awesome :) Happy hacking!
