### ISSUE TITLE
Writing a serial bootloader

### ISSUE THREAD

**Issue by Gregwar** [leaflabs/maple-bootloader#15]
Hello @mbolivar ,
I'm currently trying to write a serial bootloader and I discovered your serial-boot branch that includes the usb serial 
I've changed the LED, BUTTON & DISC pin because I'm trying it on a Maple Mini, but it seems that my computer can't enumerate the USB device, I'm getting like "Device not responding to setup address" in my syslog
Do you have any idea what I'm missing?

**Comment by Gregwar** [comment]
Sorry, I found my mistake, and I can now exchange data with the maple mini during bootloader

**Comment by colesnicov** [comment]
Hi @Gregwar How you do it? I have maple mini too but, I cannot load this...

**Comment by Gregwar** [comment]
What do you want to do exactly?

**Comment by colesnicov** [comment]
Hi Gregwar. I apologize in advance for English, I'm using google translator, I'm from Czech. I just started with one-chip and bought a maple mini straight. I'm using Linux Ubuntu on my computer. So I have Linux Ubuntu, 6Pin USB TTL UART converter with RESET pin, Maple mini, Maple IDE or Arduino IDE. And I would like to program the maple so I can put it in the serial console "Hello world" - which is the code from "File> Examples". Installing stm32duino I do the following steps: http://wiki.stm32duino.com/index.php?title=Installation.
 When trying to upload sketches to maple I get an error:
 **Archiving built core (caching) in: /tmp/arduino_cache_799888/core/core_Arduino_STM32-master_STM32F1_mapleMini_bootloader_version_original,cpu_speed_speed_72mhz,opt_osstd_d9fb38969ee7d0fdacc9752ab5a7ccd9.a
Waiting for / dev / ttyUSB0 serial ... Done
/ Home / denis / Arduino / hardware / Arduino_STM32-master / tools / linux / dfs-util / dfu-util: File: Wrong executable file format

**Comment by colesnicov** [comment]
No hope?

**Comment by rogerclarkmelbourne** [comment]
Are you actually using the bootloader from this repo or the one from my repo

github.com/rogerclarkmelbourne/stm32duino-bootloader 

?

If you are using this bootloader, there is no support as LeafLabs no longer maintain this repo or respond to issues 

I suggest you post to www.stm32duino.com
